# Generated by Django 5.1.4 on 2025-03-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_blogpost_author'),
        ('lmsapp', '0015_rename_author_course_instructor_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='lmsapp.profile'),
        ),
    ]
