# Generated by Django 5.1.4 on 2025-03-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blogpost_author'),
        ('lmsapp', '0020_lesson_video_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='lmsapp.profile'),
        ),
    ]
