# Generated by Django 5.1.4 on 2025-03-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what_you_learn',
            name='learn_image',
        ),
    ]
