# Generated by Django 5.1.4 on 2025-03-03 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_remove_what_you_learn_learn_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='require_image',
        ),
        migrations.AlterField(
            model_name='requirements',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='blogapp.blogpost'),
        ),
        migrations.AlterField(
            model_name='what_you_learn',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='what_you_learn', to='blogapp.blogpost'),
        ),
        migrations.CreateModel(
            name='What_you_learn_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_image', models.ImageField(blank=True, null=True, upload_to='learn_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='what_you_learn_images', to='blogapp.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='Who_should_attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_should_attend', to='blogapp.blogpost')),
            ],
        ),
    ]
