# Generated by Django 5.1.4 on 2025-03-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_remove_requirements_require_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogpost'),
        ),
        migrations.AlterField(
            model_name='what_you_learn',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogpost'),
        ),
        migrations.AlterField(
            model_name='what_you_learn_image',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogpost'),
        ),
        migrations.AlterField(
            model_name='who_should_attend',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogpost'),
        ),
    ]
