# Generated by Django 5.1.4 on 2025-03-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
