# Generated by Django 5.1.4 on 2025-01-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0007_checkoutaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Razorpay', max_length=50),
        ),
    ]
