# Generated by Django 5.1.4 on 2025-01-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
