# Generated by Django 5.1.4 on 2025-03-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0010_payment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='zip_code',
        ),
    ]
