# Generated by Django 5.1.4 on 2025-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0011_remove_checkoutaddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='phone',
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
