# Generated by Django 5.1.4 on 2025-03-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0012_remove_checkoutaddress_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
