# Generated by Django 5.1.4 on 2025-03-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0015_rename_author_course_instructor_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
