# Generated by Django 5.1.4 on 2025-03-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0016_remove_video_lesson_delete_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
