# Generated by Django 5.1.4 on 2025-03-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0017_remove_instructor_name_alter_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='other_name',
        ),
    ]
